INPUT:
  MIN_SIZE_TRAIN: (256,)
DATASETS:
  TRAIN: ("PIV2DSequence",)
  TEST: ("PIV2DSequence",)
  TEST_RATIO: 0.1
  TOTAL_NUM: 200
  SHUFFLE: False
  SEQUENCE_LENGTH: 5
DATALOADER:
  NUM_WORKERS: 4
MODEL:
  PREDICTOR:
    NAME: "null"
  CORRECTOR:
    NAME: "corrector"
    UPSTREAM_PREDICTOR: "pretrained_model/predictor_unpwc_plain.pth"
    COEF_CONVECTION: 0.1
    COEF_DIFFUSION: 1.0
SOLVER:
  IMS_PER_BATCH: 4
  MAX_EPOCH: 200
  BASE_LR: 0.0001
  MAX_ITER: 40000
  WEIGHT_DECAY: 0.0001
  CHECKPOINT_PERIOD: 100
TRAIN:
  LOSS:
    PHOTOMETRIC: 0.0
    VORTICITY_WARP: 1.0
    REFINE_REGULARIZER: 0.01
    CORRECTOR_DIVERGENCE: 0.1
TEST:
  BATCH_SIZE: 1
SEED: 42
VERSION: 1
DEVICE: 'cuda'
NUM_GPUS: '1'
NUM_WORKERS: '4'
DATA_DIR: './data'
OUTPUT_DIR: "./output/corrector-BS4-DIV-REFINE-SEQ5"