INPUT:
  MIN_SIZE_TRAIN: (256,)
DATASETS:
  TRAIN: ("PIV2D",)
  TEST: ("PIV2D",)
  TEST_RATIO: 0.1
DATALOADER:
  NUM_WORKERS: 4
MODEL:
  PREDICTOR:
    NAME: "pwcnet"
    FLOWNET_DEFAULT_WEIGHTS: [12.7, 5.5, 4.35, 3.9, 3.4, 1.1, 0.5]
SOLVER:
  IMS_PER_BATCH: 8
  MAX_EPOCH: 50
  BASE_LR: 0.0001
  MAX_ITER: 40000
  WEIGHT_DECAY: 0.0001
TRAIN:
  LOSS:
    PHOTOMETRIC: 1.0
    SMOOTHNESS_1ST: 3.0
    CONSISTENCY: 0.0
    DIVERGENCE_1ST: 3.0
TEST:
  BATCH_SIZE: 128
SEED: 42
VERSION: 1
DEVICE: 'cuda'
NUM_GPUS: '1'
NUM_WORKERS: '4'
DATA_DIR: './data'
OUTPUT_DIR: "./output/Predictor-Pwcnet-PSD"